CREATE TABLE llx_inbox_account(
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	label varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	imap_server varchar(255) NOT NULL,
	imap_port integer DEFAULT 993,
	imap_security varchar(50) DEFAULT 'ssl',
	imap_login varchar(255) NOT NULL,
	imap_password varchar(255) NOT NULL,
	smtp_server varchar(255),
	smtp_port integer DEFAULT 465,
	smtp_security varchar(50) DEFAULT 'ssl',
	smtp_login varchar(255),
	smtp_password varchar(255),
	allow_self_signed integer DEFAULT 0,
	signature text,
	fk_user integer DEFAULT NULL,
	sync_limit_nb integer DEFAULT 500,
	sync_limit_days integer DEFAULT 180,
	shared integer DEFAULT 0,
	status integer DEFAULT 1,
	date_creation datetime,
	tms timestamp,
	fk_user_creat integer,
	fk_user_modif integer
) ENGINE=innodb;
